/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIERNES.SGIS;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alcides Blandon
 */
public class FrmNUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmNUsuario
     */
    public FrmNUsuario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPrincipal = new javax.swing.JPanel();
        jLbDatosUsuario = new javax.swing.JLabel();
        jLbCodigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLbNombres = new javax.swing.JLabel();
        jTFNombres = new javax.swing.JTextField();
        jLbApellidos = new javax.swing.JLabel();
        jTFApellidos = new javax.swing.JTextField();
        jLbCorreo = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jRBMujer = new javax.swing.JRadioButton();
        jRBHombre = new javax.swing.JRadioButton();
        jLbDireccion = new javax.swing.JLabel();
        jSPDireccion = new javax.swing.JScrollPane();
        jTADireccion = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLbPrivilegios = new javax.swing.JLabel();
        jCBLectura = new javax.swing.JCheckBox();
        jCBEscritura = new javax.swing.JCheckBox();
        jCBPropietario = new javax.swing.JCheckBox();
        jLbCargo = new javax.swing.JLabel();
        jCBCargo = new javax.swing.JComboBox<>();
        jBAgregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPPanelSecundario = new javax.swing.JPanel();
        jSPPanel2 = new javax.swing.JScrollPane();
        jTbUsuarios = new javax.swing.JTable();

        jLbDatosUsuario.setText("Datos del Usuario");

        jLbCodigo.setText("Codigo");

        jLbNombres.setText("*Nombres");

        jLbApellidos.setText("*Apellidos");

        jLbCorreo.setText("Correo");

        jTFCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCorreoFocusLost(evt);
            }
        });
        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCorreoKeyTyped(evt);
            }
        });

        jRBMujer.setText("Mujer");

        jRBHombre.setText("Hombre");

        jLbDireccion.setText("Direccion");

        jTADireccion.setColumns(20);
        jTADireccion.setRows(5);
        jSPDireccion.setViewportView(jTADireccion);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLbPrivilegios.setText("Privilegios");

        jCBLectura.setText("Lectura");

        jCBEscritura.setText("Escritura");

        jCBPropietario.setText("Propietario");

        jLbCargo.setText("Cargo");

        jCBCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Personal", "Invitado" }));

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addComponent(jLbDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(jSPDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPrincipalLayout.createSequentialGroup()
                                .addComponent(jLbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLbNombres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLbApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLbDatosUsuario))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPrincipalLayout.createSequentialGroup()
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPrincipalLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPrincipalLayout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPrincipalLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLbPrivilegios)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBLectura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBEscritura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBPropietario)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLbCargo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPrincipalLayout.createSequentialGroup()
                                .addComponent(jLbCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBHombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jRBMujer)))
                        .addGap(40, 40, 40))))
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jBAgregar)
                .addGap(93, 93, 93)
                .addComponent(jBEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLbDatosUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCodigo)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbNombres)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbApellidos)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCorreo)
                    .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBMujer)
                    .addComponent(jRBHombre))
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLbDireccion))
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSPDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbPrivilegios)
                    .addComponent(jCBLectura)
                    .addComponent(jCBEscritura)
                    .addComponent(jCBPropietario)
                    .addComponent(jLbCargo)
                    .addComponent(jCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBEliminar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Correo", "Direccion", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jSPPanel2.setViewportView(jTbUsuarios);

        javax.swing.GroupLayout jPPanelSecundarioLayout = new javax.swing.GroupLayout(jPPanelSecundario);
        jPPanelSecundario.setLayout(jPPanelSecundarioLayout);
        jPPanelSecundarioLayout.setHorizontalGroup(
            jPPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );
        jPPanelSecundarioLayout.setVerticalGroup(
            jPPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPPanelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        if (jTFNombres.getText().equals("") && jTFApellidos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Correctamente \n"
                    + "Los campos con * son obligatorios", "Campos obligatorios", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jTbUsuarios.getModel();

            Object[] fila = new Object[5];
            fila[0] = jTFNombres.getText();
            fila[1] = jTFApellidos.getText();
            fila[2] = jTFCorreo.getText();
            fila[3] = jTADireccion.getText();
            fila[4] = jCBCargo.getSelectedItem().toString();

            modelo.addRow(fila);
            jTbUsuarios.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Registrado Correctamente");

            jTFCodigo.setText("");
            jTFNombres.setText("");
            jTFApellidos.setText("");
            jTFCorreo.setText("");
            jTADireccion.setText("");

            jCBLectura.setSelected(false);
            jCBEscritura.setSelected(false);
            jCBPropietario.setSelected(false);

            jRBHombre.setSelected(false);
            jRBMujer.setSelected(false);
            jTFNombres.requestFocus();

        }

    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTbUsuarios.getModel();

        int a = jTbUsuarios.getSelectedRow();

        if (a < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Eliminar Registro?");
            if (JOptionPane.OK_OPTION == confirmar) {
                model.removeRow(a);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }

    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTFCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCorreoFocusLost
        // TODO add your handling code here:
        if(vCorreo(jTFCorreo.getText())){
            
        }else{
            JOptionPane.showMessageDialog(null, "Correo Incorrecto", "Validar "
                    + "Correo", JOptionPane.INFORMATION_MESSAGE);
            jTFCorreo.requestFocus();
        }
    }//GEN-LAST:event_jTFCorreoFocusLost

    private void jTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCorreoKeyTyped
        // TODO add your handling code here:
        
        char car = evt.getKeyChar();
        if((car<'0' || car >'9') && jTFCodigo.getText().contains(".")
                && (car!=(char)KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solamente Numeros", "Validar "
                    + "Numeros", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jTFCorreoKeyTyped

    public boolean vCorreo(String correo) {
        Pattern pat = null;
        Matcher mat = null;

        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+"
                + "\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JComboBox<String> jCBCargo;
    private javax.swing.JCheckBox jCBEscritura;
    private javax.swing.JCheckBox jCBLectura;
    private javax.swing.JCheckBox jCBPropietario;
    private javax.swing.JLabel jLbApellidos;
    private javax.swing.JLabel jLbCargo;
    private javax.swing.JLabel jLbCodigo;
    private javax.swing.JLabel jLbCorreo;
    private javax.swing.JLabel jLbDatosUsuario;
    private javax.swing.JLabel jLbDireccion;
    private javax.swing.JLabel jLbNombres;
    private javax.swing.JLabel jLbPrivilegios;
    private javax.swing.JPanel jPPanelSecundario;
    private javax.swing.JPanel jPrincipal;
    private javax.swing.JRadioButton jRBHombre;
    private javax.swing.JRadioButton jRBMujer;
    private javax.swing.JScrollPane jSPDireccion;
    private javax.swing.JScrollPane jSPPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTADireccion;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFNombres;
    private javax.swing.JTable jTbUsuarios;
    // End of variables declaration//GEN-END:variables
}
