/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIERNES.SGIS;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alcides Blandon
 */
public class JIFComprobantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFComprobantes
     */
    public JIFComprobantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDebeHaber = new javax.swing.ButtonGroup();
        jLbTituloRegistroC = new javax.swing.JLabel();
        jPCargarAsiento = new javax.swing.JPanel();
        jLbFechaCargarA = new javax.swing.JLabel();
        jCBFechaCargarA = new javax.swing.JComboBox<>();
        jLbAnnio = new javax.swing.JLabel();
        jLbGastos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCBCuenta = new javax.swing.JComboBox<>();
        jLbAuxiliar = new javax.swing.JLabel();
        jCBAxuiliar = new javax.swing.JComboBox<>();
        jLbSueldoySalarios = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jBtnX = new javax.swing.JButton();
        jLbConcepto = new javax.swing.JLabel();
        jTFConcepto = new javax.swing.JTextField();
        jBtnCheck = new javax.swing.JButton();
        jPIngresarMonto = new javax.swing.JPanel();
        jRBHaber = new javax.swing.JRadioButton();
        jRBDebe = new javax.swing.JRadioButton();
        jTFMonto = new javax.swing.JTextField();
        jLbMonto = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jPComprobante = new javax.swing.JPanel();
        jSPComprobante = new javax.swing.JScrollPane();
        jTbComprobante = new javax.swing.JTable();
        jBRegistrarComprobante = new javax.swing.JButton();

        jLbTituloRegistroC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLbTituloRegistroC.setText("Registro de Comprobantes");

        jPCargarAsiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Asiento"));

        jLbFechaCargarA.setText("Fecha:");

        jCBFechaCargarA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril ", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));

        jLbAnnio.setText("2021");

        jLbGastos.setText("Gastos");

        jLabel1.setText("Cuenta");

        jCBCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3000", "5000" }));

        jLbAuxiliar.setText("Auxiliar");

        jCBAxuiliar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3001", "5001" }));

        jLbSueldoySalarios.setText("Sueldos y Salarios");

        jBtnX.setText("√");

        jLbConcepto.setText("Concepto");

        jBtnCheck.setText("X");

        javax.swing.GroupLayout jPCargarAsientoLayout = new javax.swing.GroupLayout(jPCargarAsiento);
        jPCargarAsiento.setLayout(jPCargarAsientoLayout);
        jPCargarAsientoLayout.setHorizontalGroup(
            jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                        .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLbAuxiliar))
                            .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                                .addComponent(jLbFechaCargarA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbGastos)
                                    .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                                        .addComponent(jCBFechaCargarA, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLbAnnio)))))
                        .addGap(32, 32, 32)
                        .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbSueldoySalarios)
                            .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                                .addComponent(jCBAxuiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                        .addComponent(jLbConcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPCargarAsientoLayout.setVerticalGroup(
            jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCargarAsientoLayout.createSequentialGroup()
                        .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCBFechaCargarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbAnnio))
                            .addComponent(jLbFechaCargarA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCargarAsientoLayout.createSequentialGroup()
                        .addComponent(jLbSueldoySalarios)
                        .addGap(20, 20, 20)))
                .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbAuxiliar)
                    .addComponent(jCBAxuiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCargarAsientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbConcepto)
                    .addComponent(jTFConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnX))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPIngresarMonto.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Monto"));

        bgDebeHaber.add(jRBHaber);
        jRBHaber.setText("Haber");

        bgDebeHaber.add(jRBDebe);
        jRBDebe.setText("Debe");

        jLbMonto.setText("Monto");

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPIngresarMontoLayout = new javax.swing.GroupLayout(jPIngresarMonto);
        jPIngresarMonto.setLayout(jPIngresarMontoLayout);
        jPIngresarMontoLayout.setHorizontalGroup(
            jPIngresarMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPIngresarMontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBDebe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBHaber))
            .addGroup(jPIngresarMontoLayout.createSequentialGroup()
                .addGroup(jPIngresarMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPIngresarMontoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPIngresarMontoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLbMonto))
                    .addGroup(jPIngresarMontoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jBAceptar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPIngresarMontoLayout.setVerticalGroup(
            jPIngresarMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIngresarMontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPIngresarMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBHaber)
                    .addComponent(jRBDebe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbMonto)
                .addGap(7, 7, 7)
                .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAceptar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTbComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Auxilidar", "Concepto", "Debe", "Haber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jSPComprobante.setViewportView(jTbComprobante);

        javax.swing.GroupLayout jPComprobanteLayout = new javax.swing.GroupLayout(jPComprobante);
        jPComprobante.setLayout(jPComprobanteLayout);
        jPComprobanteLayout.setHorizontalGroup(
            jPComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPComprobante)
        );
        jPComprobanteLayout.setVerticalGroup(
            jPComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComprobanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
        );

        jBRegistrarComprobante.setText("Registrar Comprobante");
        jBRegistrarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLbTituloRegistroC, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPCargarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPIngresarMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBRegistrarComprobante)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPIngresarMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLbTituloRegistroC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPCargarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBRegistrarComprobante)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarComprobanteActionPerformed
        // TODO add your handling code here:
        if (jTFConcepto.getText().equals("") && jTFMonto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Correctamente \n"
                    + "Los campos con * son obligatorios", "Campos obligatorios", JOptionPane.ERROR_MESSAGE);
        } else {

            DefaultTableModel modelo = (DefaultTableModel) jTbComprobante.getModel();

            Object[] fila = new Object[5];
            fila[0] = jCBCuenta.getSelectedItem().toString();
            fila[1] = jCBAxuiliar.getSelectedItem().toString();
            fila[2] = jTFConcepto.getText();
            
            if(debeHaber){
                fila[3] = valorRadio;
                
            }else{
                fila[4] = valorRadio;
            }
            
            modelo.addRow(fila);
            jTbComprobante.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Registrado Correctamente");

            jTFConcepto.setText("");
            jTFMonto.setText("");

        }

    }//GEN-LAST:event_jBRegistrarComprobanteActionPerformed

    String valorRadio;
    boolean debeHaber = false;
    
    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        
        if(jTFMonto.getText().equals("") && (jRBDebe.isSelected() == false)
                || jTFMonto.getText().equals("") && (jRBHaber.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Debe llenar los campos y seleccionar entre debe o haber");
        }else{
            
            if (jRBDebe.isSelected() == true) {
                valorRadio = jTFMonto.getText();
                debeHaber = true;
            } else {
                valorRadio = jTFMonto.getText();
                debeHaber = false;
            }
        }
        
        
        jTFMonto.setText("");
    }//GEN-LAST:event_jBAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDebeHaber;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBRegistrarComprobante;
    private javax.swing.JButton jBtnCheck;
    private javax.swing.JButton jBtnX;
    private javax.swing.JComboBox<String> jCBAxuiliar;
    private javax.swing.JComboBox<String> jCBCuenta;
    private javax.swing.JComboBox<String> jCBFechaCargarA;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbAnnio;
    private javax.swing.JLabel jLbAuxiliar;
    private javax.swing.JLabel jLbConcepto;
    private javax.swing.JLabel jLbFechaCargarA;
    private javax.swing.JLabel jLbGastos;
    private javax.swing.JLabel jLbMonto;
    private javax.swing.JLabel jLbSueldoySalarios;
    private javax.swing.JLabel jLbTituloRegistroC;
    private javax.swing.JPanel jPCargarAsiento;
    private javax.swing.JPanel jPComprobante;
    private javax.swing.JPanel jPIngresarMonto;
    private javax.swing.JRadioButton jRBDebe;
    private javax.swing.JRadioButton jRBHaber;
    private javax.swing.JScrollPane jSPComprobante;
    private javax.swing.JTextField jTFConcepto;
    private javax.swing.JTextField jTFMonto;
    private javax.swing.JTable jTbComprobante;
    // End of variables declaration//GEN-END:variables
}
