/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIERNES.SGIS;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alcides Blandon
 */
public class JIFInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventario
     */
    public JIFInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPInventario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbInventario = new javax.swing.JTable();
        jPProducto = new javax.swing.JPanel();
        jLbID = new javax.swing.JLabel();
        jTFID = new javax.swing.JTextField();
        jLbNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFTipo = new javax.swing.JTextField();
        jLbTipo = new javax.swing.JLabel();
        jLbCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jTFColor = new javax.swing.JTextField();
        jLbColor = new javax.swing.JLabel();
        jTFTalla = new javax.swing.JTextField();
        jLbTalla = new javax.swing.JLabel();
        jTFPrecio = new javax.swing.JTextField();
        jLbPrecio = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();
        jLbAgregarInventario = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();

        jPInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        jTbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo", "Cantidad", "Color", "Talla", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbInventario);

        javax.swing.GroupLayout jPInventarioLayout = new javax.swing.GroupLayout(jPInventario);
        jPInventario.setLayout(jPInventarioLayout);
        jPInventarioLayout.setHorizontalGroup(
            jPInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPInventarioLayout.setVerticalGroup(
            jPInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInventarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLbID.setText("ID");

        jLbNombre.setText("Nombre");

        jLbTipo.setText("Tipo");

        jLbCantidad.setText("Cantidad");

        jLbColor.setText("Color");

        jLbTalla.setText("Talla");

        jLbPrecio.setText("Precio");

        javax.swing.GroupLayout jPProductoLayout = new javax.swing.GroupLayout(jPProducto);
        jPProducto.setLayout(jPProductoLayout);
        jPProductoLayout.setHorizontalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLbID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbNombre)
                        .addGap(27, 27, 27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLbTipo)))
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLbCantidad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFColor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLbColor)))
                .addGap(16, 16, 16)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLbTalla))
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLbPrecio)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPProductoLayout.setVerticalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPProductoLayout.createSequentialGroup()
                            .addComponent(jLbPrecio)
                            .addGap(36, 36, 36)))
                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPProductoLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPProductoLayout.createSequentialGroup()
                                    .addComponent(jLbColor)
                                    .addGap(36, 36, 36))
                                .addGroup(jPProductoLayout.createSequentialGroup()
                                    .addComponent(jLbTalla)
                                    .addGap(12, 12, 12)
                                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPProductoLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPProductoLayout.createSequentialGroup()
                                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLbID)
                                        .addComponent(jLbNombre)
                                        .addComponent(jLbTipo)
                                        .addComponent(jLbCantidad))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBtnActualizar.setText("♻");
        jBtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarActionPerformed(evt);
            }
        });

        jLbAgregarInventario.setText("Agregar un nuevo producto a Inventario");

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jBEditar)
                        .addGap(52, 52, 52)
                        .addComponent(jBEliminar)
                        .addGap(108, 108, 108)
                        .addComponent(jBtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLbAgregarInventario)
                        .addGap(152, 152, 152)
                        .addComponent(jBAgregar)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditar)
                    .addComponent(jBEliminar)
                    .addComponent(jBtnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbAgregarInventario)
                    .addComponent(jBAgregar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        if (jTFID.getText().equals("") && jTFCantidad.getText().equals("")
                && jTFColor.getText().equals("") && jTFNombre.getText().equals("")
                && jTFPrecio.getText().equals("") && jTFTalla.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Correctamente \n"
                    + "Los campos con * son obligatorios", "Campos obligatorios", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jTbInventario.getModel();

            Object[] fila = new Object[7];
            fila[0] = jTFCantidad.getText();
            fila[1] = jTFColor.getText();
            fila[2] = jTFID.getText();
            fila[3] = jTFNombre.getText();
            fila[4] = jTFPrecio.getText();
            fila[5] = jTFTalla.getText();
            fila[6] = jTFTipo.getText();

            modelo.addRow(fila);
            jTbInventario.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Registrado Correctamente");

            jTFCantidad.setText("");
            jTFColor.setText("");
            jTFID.setText("");
            jTFNombre.setText("");
            jTFPrecio.setText("");
            jTFTalla.setText("");
            jTFTipo.setText("");
    }//GEN-LAST:event_jBAgregarActionPerformed
    }
    private void jBtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarActionPerformed
        // TODO add your handling code here:
        jTFCantidad.setText("");
        jTFColor.setText("");
        jTFID.setText("");
        jTFNombre.setText("");
        jTFPrecio.setText("");
        jTFTalla.setText("");
        jTFTipo.setText("");
    }//GEN-LAST:event_jBtnActualizarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTbInventario.getModel();

        int a = jTbInventario.getSelectedRow();

        if (a < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Eliminar Registro?");
            if (JOptionPane.OK_OPTION == confirmar) {
                model.removeRow(a);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTbInventario.getModel();

        int a = jTbInventario.getSelectedRow();

        if (a < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null, "¿Modificar?");
            if (JOptionPane.OK_OPTION == confirmar) {
                String menu = JOptionPane.showInputDialog("Elija la columna a modificar\n"
                        + "1. ID\n"
                        + "2. Nombre\n"
                        + "3. Tipo\n"
                        + "4. Cantidad\n"
                        + "5. Color\n"
                        + "6. Talla\n"
                        + "7. Precio\n");
                switch (menu) {
                    case "1":
                        int idColumn = 0;
                        String id = JOptionPane.showInputDialog("Nuevo ID");
                        model.setValueAt(id, a, idColumn);
                        break;
                    case "2":
                        int nombreColumn = 1;
                        String nombre = JOptionPane.showInputDialog("Nuevo Nombre");
                        model.setValueAt(nombre, a, nombreColumn);
                        break;
                    case "3":
                        int tipoColumn = 2;
                        String tipo = JOptionPane.showInputDialog("Nuevo Tipo");
                        model.setValueAt(tipo, a, tipoColumn);
                        break;
                    case "4":
                        int cantidadColumn = 3;
                        String cantidad = JOptionPane.showInputDialog("Nueva Cantidad");
                        model.setValueAt(cantidad, a, cantidadColumn);
                        break;
                    case "5":
                        int colorColumn = 4;
                        String color = JOptionPane.showInputDialog("Nuevo Color");
                        model.setValueAt(color, a, colorColumn);
                        break;
                    case "6":
                        int tallaColumn = 5;
                        String talla = JOptionPane.showInputDialog("Nueva Talla");
                        model.setValueAt(talla, a, tallaColumn);
                        break;

                    case "7":
                        int precioColumn = 6;
                        String precio = JOptionPane.showInputDialog("Nuevo precio");
                        model.setValueAt(precio, a, precioColumn);
                        break;

                    default:
                        JOptionPane.showMessageDialog(null, "No entiendo que quieres decir", "Algo no esta bien", JOptionPane.ERROR_MESSAGE);
                        break;
                }

                JOptionPane.showMessageDialog(null, "Registro Modificado");
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JLabel jLbAgregarInventario;
    private javax.swing.JLabel jLbCantidad;
    private javax.swing.JLabel jLbColor;
    private javax.swing.JLabel jLbID;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JLabel jLbPrecio;
    private javax.swing.JLabel jLbTalla;
    private javax.swing.JLabel jLbTipo;
    private javax.swing.JPanel jPInventario;
    private javax.swing.JPanel jPProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPrecio;
    private javax.swing.JTextField jTFTalla;
    private javax.swing.JTextField jTFTipo;
    private javax.swing.JTable jTbInventario;
    // End of variables declaration//GEN-END:variables
}
