/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.uni.view;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import proyecto.uni.controller.DatosGenerales;
import proyecto.uni.model.InteresSimple;

public class IntSimple extends javax.swing.JFrame {

    private List<JRadioButton> radioButtons;
    private List<String> comboBoxSimple;
    private List<JButton> botonesIS;
    private List<JTextField> textFieldIS;
    private List<JLabel> labelsIS;

    DatosGenerales datos = new DatosGenerales();
    double monto = 0;
    double capital = 0;
    double tasa = 0;
    double periodo = 0;

    public IntSimple() {
        initComponents();
        comboBoxSimple = new ArrayList<>();
        radioButtons = new ArrayList<>();
        botonesIS = new ArrayList<>();
        textFieldIS = new ArrayList<>();
        labelsIS = new ArrayList<>();

        radioButtons.add(RadioMonto);
        radioButtons.add(RadioCapital);
        radioButtons.add(RadioTasa);
        radioButtons.add(RadioPeriodo);

        comboBoxSimple.add(CmbPerido.getItemAt(0));
        comboBoxSimple.add(CmbPerido.getItemAt(1));
        comboBoxSimple.add(CmbPerido.getItemAt(2));
        comboBoxSimple.add(CmbPerido.getItemAt(3));
        comboBoxSimple.add(CmbPerido.getItemAt(4));
        comboBoxSimple.add(CmbPerido.getItemAt(5));
        comboBoxSimple.add(CmbPerido.getItemAt(6));
        comboBoxSimple.add(CmbPerido.getItemAt(7));

        textFieldIS.add(TxtMonto);
        textFieldIS.add(TxtCapital);
        textFieldIS.add(TxtTasa);
        textFieldIS.add(TxtPeriodo);

        botonesIS.add(BtnLimpiar);
        botonesIS.add(BtnCalcular);
        botonesIS.add(BtnSalir);

        //datos.agregarDatos(botonesIS, textFieldIS, radioButtons, labelsIS);

    }

    /**
     * Creates new form IntSimple
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupSimple = new javax.swing.ButtonGroup();
        btGroupInteresSimple = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPanel = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblSelecione = new javax.swing.JLabel();
        RadioMonto = new javax.swing.JRadioButton();
        TxtMonto = new javax.swing.JTextField();
        RadioCapital = new javax.swing.JRadioButton();
        TxtCapital = new javax.swing.JTextField();
        RadioTasa = new javax.swing.JRadioButton();
        TxtTasa = new javax.swing.JTextField();
        LblCapítalizacion = new javax.swing.JLabel();
        RadioPeriodo = new javax.swing.JRadioButton();
        TxtPeriodo = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        CmbPerido = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(238, 238, 238));
        JPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPanel.setForeground(new java.awt.Color(238, 238, 238));

        LblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(0, 173, 181));
        LblTitulo.setText("Interes Simple");

        LblSelecione.setForeground(new java.awt.Color(0, 173, 181));
        LblSelecione.setText("Seleccione que variable a calcular.");

        BtnGroupSimple.add(RadioMonto);
        RadioMonto.setForeground(new java.awt.Color(0, 173, 181));
        RadioMonto.setText("Monto");
        RadioMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMontoActionPerformed(evt);
            }
        });

        TxtMonto.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMontoActionPerformed(evt);
            }
        });

        BtnGroupSimple.add(RadioCapital);
        RadioCapital.setForeground(new java.awt.Color(0, 173, 181));
        RadioCapital.setText("Capital");
        RadioCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCapitalActionPerformed(evt);
            }
        });

        TxtCapital.setBackground(new java.awt.Color(255, 255, 255));

        BtnGroupSimple.add(RadioTasa);
        RadioTasa.setForeground(new java.awt.Color(0, 173, 181));
        RadioTasa.setText("Tasa");
        RadioTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTasaActionPerformed(evt);
            }
        });

        TxtTasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTasaActionPerformed(evt);
            }
        });

        LblCapítalizacion.setBackground(new java.awt.Color(0, 0, 0));
        LblCapítalizacion.setForeground(new java.awt.Color(0, 173, 181));
        LblCapítalizacion.setText("Capitalizable");

        BtnGroupSimple.add(RadioPeriodo);
        RadioPeriodo.setForeground(new java.awt.Color(0, 173, 181));
        RadioPeriodo.setText("Período");
        RadioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPeriodoActionPerformed(evt);
            }
        });

        TxtPeriodo.setBackground(new java.awt.Color(255, 255, 255));

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtnSalir.setForeground(new java.awt.Color(0, 173, 181));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtnCalcular.setForeground(new java.awt.Color(0, 173, 181));
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setForeground(new java.awt.Color(0, 173, 181));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        CmbPerido.setForeground(new java.awt.Color(0, 0, 0));
        CmbPerido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anual", "Mensual", "Semestral ", "Trimestral", "Cuatrimestral", "Bimestrestral ", "Dias 360", "Dias 365" }));
        CmbPerido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbPeridoMouseClicked(evt);
            }
        });
        CmbPerido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbPeridoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(LblTitulo)
                .addGap(270, 270, 270))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LblSelecione)
                        .addGap(56, 56, 56))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RadioPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RadioTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RadioCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RadioMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCapital, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTasa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPeriodo)
                                    .addComponent(TxtMonto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblCapítalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LblTitulo)
                .addGap(35, 35, 35)
                .addComponent(LblSelecione)
                .addGap(27, 27, 27)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioMonto)
                    .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioCapital)
                    .addComponent(TxtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioTasa)
                    .addComponent(TxtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbPerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioPeriodo)
                    .addComponent(TxtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCapítalizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jTabbedPane1.addTab("Interes Simple", JPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Convertir Periodo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMontoActionPerformed

    private void TxtTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTasaActionPerformed

    private void RadioMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMontoActionPerformed
        if (radioButtons.get(0).isSelected()) {
            TxtMonto.setEnabled(false);
            TxtPeriodo.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtTasa.setEnabled(true);
        }
    }//GEN-LAST:event_RadioMontoActionPerformed

    private void RadioCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCapitalActionPerformed
        if (radioButtons.get(1).isSelected()) {
            TxtCapital.setEnabled(false);
            TxtPeriodo.setEnabled(true);
            TxtMonto.setEnabled(true);
            TxtTasa.setEnabled(true);
        }
    }//GEN-LAST:event_RadioCapitalActionPerformed

    private void RadioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPeriodoActionPerformed
        if (radioButtons.get(3).isSelected()) {
            TxtPeriodo.setEnabled(false);
            TxtMonto.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtTasa.setEnabled(true);
        }
    }//GEN-LAST:event_RadioPeriodoActionPerformed


    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed

        if (radioButtons.get(0).isSelected()) {
            capital = Double.parseDouble(TxtCapital.getText());
            tasa = Double.parseDouble(TxtTasa.getText());
            periodo = Double.parseDouble(TxtPeriodo.getText());
            InteresSimple is = new InteresSimple(monto, capital, tasa, periodo, radioButtons, comboBoxSimple);
            is.cISMonto(is.getCapital(), is.getTasa(), is.getPerido());
            TxtMonto.setText(String.valueOf(is.getMonto()));
        }
        
        if (radioButtons.get(1).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText());
            tasa = Double.parseDouble(TxtTasa.getText());
            periodo = Double.parseDouble(TxtPeriodo.getText());
            InteresSimple is = new InteresSimple(monto, capital, tasa, periodo, radioButtons, comboBoxSimple);
            is.cISCapital(is.getMonto(), is.getTasa(), is.getPerido());
            TxtCapital.setText(String.valueOf(is.getCapital()));
        }
        
         if (radioButtons.get(2).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText());
            capital = Double.parseDouble(TxtCapital.getText());
            periodo = Double.parseDouble(TxtPeriodo.getText());
            InteresSimple is = new InteresSimple(monto, capital, tasa, periodo, radioButtons, comboBoxSimple);
            is.cISTasa(is.getMonto(), is.getCapital(), is.getPerido());
            TxtTasa.setText(String.valueOf(is.getTasa()));
        }
         
          if (radioButtons.get(3).isSelected()) {
            monto = Double.parseDouble(TxtMonto.getText());
            capital = Double.parseDouble(TxtCapital.getText());
            tasa = Double.parseDouble(TxtTasa.getText());
            InteresSimple is = new InteresSimple(monto, capital, tasa, periodo, radioButtons, comboBoxSimple);
            is.cISPeriodo(is.getMonto(), is.getCapital(), is.getTasa());
            TxtPeriodo.setText(String.valueOf(is.getPerido()));
        }


    }//GEN-LAST:event_BtnCalcularActionPerformed


    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
        FrmMenu r = new FrmMenu();
        r.setVisible(true);    }//GEN-LAST:event_BtnSalirActionPerformed

    private void RadioTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTasaActionPerformed
        if (radioButtons.get(2).isSelected()) {
            TxtTasa.setEnabled(false);
            TxtMonto.setEnabled(true);
            TxtCapital.setEnabled(true);
            TxtPeriodo.setEnabled(true);
        }
    }//GEN-LAST:event_RadioTasaActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        InteresSimple interesSimple = new InteresSimple();
        interesSimple.limpiar(datos.getTextFieldsIS());

    }//GEN-LAST:event_BtnLimpiarActionPerformed


    private void CmbPeridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPeridoActionPerformed
       
    }//GEN-LAST:event_CmbPeridoActionPerformed

    private void CmbPeridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbPeridoMouseClicked
        if (CmbPerido.getItemAt(0).equals("Anual")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Años");
        }
        if (CmbPerido.getItemAt(1).equals("Mensual")) {
            LblCapítalizacion.setText("Debe ingresar periodo en meses");
        }
        if (CmbPerido.getItemAt(2).equals("Semestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Semestres");
        }
        if (CmbPerido.getItemAt(3).equals("Trimestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Trimestre");
        }
        if (CmbPerido.getItemAt(4).equals("Cuatrimestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Cuatrimestre");
        }
        if (CmbPerido.getItemAt(5).equals("Bimestral")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Bimestre");
        }
        if (CmbPerido.getItemAt(6).equals("Dias 360")) {
            LblCapítalizacion.setText("Debe ingresar periodo Dias 360");
        }
        if (CmbPerido.getItemAt(7).equals("Dias 365")) {
            LblCapítalizacion.setText("Debe ingresar periodo en Dias 365");
        }
    }//GEN-LAST:event_CmbPeridoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntSimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCalcular;
    private javax.swing.ButtonGroup BtnGroupSimple;
    private javax.swing.JButton BtnLimpiar;
    public javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> CmbPerido;
    private javax.swing.JPanel JPanel;
    public javax.swing.JLabel LblCapítalizacion;
    private javax.swing.JLabel LblSelecione;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JRadioButton RadioCapital;
    private javax.swing.JRadioButton RadioMonto;
    private javax.swing.JRadioButton RadioPeriodo;
    private javax.swing.JRadioButton RadioTasa;
    private javax.swing.JTextField TxtCapital;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtPeriodo;
    private javax.swing.JTextField TxtTasa;
    private javax.swing.ButtonGroup btGroupInteresSimple;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
