/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Library.Objetos;
import ViewModels.ClientesVM;
import ViewModels.ConfiguracionesVM;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Alcides Blandon
 */
public class Sistema extends javax.swing.JFrame {

    private final List<JRadioButton> radio;

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();

        //Codigo Configuracion
        this.radio = new ArrayList();
        this.radio.add(RadioButtonDolares);
        this.radio.add(RadioButtonCordobas);
        config = new ConfiguracionesVM(radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMonedas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TFBuscarCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PClientesPago = new javax.swing.JPanel();
        ButtonClienteCancelar = new javax.swing.JButton();
        ButtonClienteAgregar = new javax.swing.JButton();
        TabbedPaneClientesPago = new javax.swing.JTabbedPane();
        PTPClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LabelClienteId = new javax.swing.JLabel();
        LabelClienteNombre = new javax.swing.JLabel();
        TextFieldClienteId = new javax.swing.JTextField();
        TextFieldClienteNombre = new javax.swing.JTextField();
        LabelClienteApellido = new javax.swing.JLabel();
        TextFieldClienteApellido = new javax.swing.JTextField();
        LabelClienteEmail = new javax.swing.JLabel();
        TextFieldClienteEmail = new javax.swing.JTextField();
        LabelClienteTelefono = new javax.swing.JLabel();
        TextFieldClienteTelefono = new javax.swing.JTextField();
        TextFieldClienteDireccion = new javax.swing.JTextField();
        LabelClienteDireccion = new javax.swing.JLabel();
        LabelimageCliente = new javax.swing.JLabel();
        checkboxCredito = new javax.swing.JCheckBox();
        PTPPagos = new javax.swing.JPanel();
        labelClientePagoNombre = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelClienteDeuda = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelClientePago = new javax.swing.JLabel();
        labelClientePago1 = new javax.swing.JLabel();
        labelClienteTicket = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelClienteFechaPago = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelClienteCuotasMes = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelClienteFechaIntereses = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelClienteintereses = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelClienteCuotas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TextFieldClientesCuotas = new javax.swing.JTextField();
        labelClienteTicketIntereses = new javax.swing.JLabel();
        labelClientePago2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelClienteInteresesPago = new javax.swing.JLabel();
        labelReportPagos = new javax.swing.JLabel();
        TextFieldClientesPago = new javax.swing.JTextField();
        RadioButtonIntereses = new javax.swing.JRadioButton();
        RadioButtonCuotas1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        TabbedPaneClientesPago2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableClientes = TableClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientesReport = TableClientesReport = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jLabel5 = new javax.swing.JLabel();
        ButtonClientePaginaRight0 = new javax.swing.JButton();
        SpinnerPaginasCliente = new javax.swing.JSpinner();
        ButtonClientePaginaLeft0 = new javax.swing.JButton();
        ButtonClientePaginaLeft = new javax.swing.JButton();
        ButtonClientePaginaRight = new javax.swing.JButton();
        LabelClientePaginador = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        RadioButtonDolares = new javax.swing.JRadioButton();
        RadioButtonCordobas = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        ButtonVentas = new javax.swing.JButton();
        ButtonClientes1 = new javax.swing.JButton();
        ButtonConfiguracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1190, 720));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 57));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema punto de ventas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        TabbedPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPanePrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabbedPanePrincipal.setForeground(new java.awt.Color(255, 255, 255));
        TabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2123, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Ventas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 106, 124));
        jLabel2.setText("Clientes");

        TFBuscarCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 106, 124));
        jLabel9.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(293, 293, 293)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1396, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TFBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
        );

        PClientesPago.setBackground(new java.awt.Color(255, 255, 255));
        PClientesPago.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ButtonClienteCancelar.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClienteCancelar.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClienteCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancelar.png"))); // NOI18N
        ButtonClienteCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClienteCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClienteCancelarActionPerformed(evt);
            }
        });

        ButtonClienteAgregar.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClienteAgregar.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClienteAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Agregar.png"))); // NOI18N
        ButtonClienteAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClienteAgregarActionPerformed(evt);
            }
        });

        TabbedPaneClientesPago.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneClientesPagoStateChanged(evt);
            }
        });

        PTPClientes.setBackground(new java.awt.Color(255, 255, 255));
        PTPClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 106, 124));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informacion del Cliente");

        LabelClienteId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteId.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteId.setText("ID");

        LabelClienteNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteNombre.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteNombre.setText("Nombre");

        TextFieldClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldClienteIdActionPerformed(evt);
            }
        });
        TextFieldClienteId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteIdKeyTyped(evt);
            }
        });

        TextFieldClienteNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteNombreKeyTyped(evt);
            }
        });

        LabelClienteApellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteApellido.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteApellido.setText("Apellido");

        TextFieldClienteApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteApellidoKeyTyped(evt);
            }
        });

        LabelClienteEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteEmail.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteEmail.setText("Email");

        TextFieldClienteEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteEmailKeyReleased(evt);
            }
        });

        LabelClienteTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteTelefono.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteTelefono.setText("Telefono");

        TextFieldClienteTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldClienteTelefonoKeyTyped(evt);
            }
        });

        TextFieldClienteDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldClienteDireccionKeyReleased(evt);
            }
        });

        LabelClienteDireccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelClienteDireccion.setForeground(new java.awt.Color(70, 106, 124));
        LabelClienteDireccion.setText("Dirección");

        LabelimageCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelimageCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-add-user-male-skin-type-7-48.png"))); // NOI18N
        LabelimageCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelimageCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelimageCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelimageClienteMouseClicked(evt);
            }
        });

        checkboxCredito.setText("Credito");

        javax.swing.GroupLayout PTPClientesLayout = new javax.swing.GroupLayout(PTPClientes);
        PTPClientes.setLayout(PTPClientesLayout);
        PTPClientesLayout.setHorizontalGroup(
            PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PTPClientesLayout.createSequentialGroup()
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTPClientesLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(LabelimageCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTPClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PTPClientesLayout.createSequentialGroup()
                                .addComponent(LabelClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelClienteDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PTPClientesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelClienteEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PTPClientesLayout.createSequentialGroup()
                                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LabelClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldClienteEmail)
                                        .addComponent(TextFieldClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTPClientesLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxCredito)
                                    .addGroup(PTPClientesLayout.createSequentialGroup()
                                        .addComponent(TextFieldClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextFieldClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PTPClientesLayout.setVerticalGroup(
            PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTPClientesLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelimageCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelClienteId)
                    .addComponent(LabelClienteNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelClienteApellido)
                    .addComponent(LabelClienteEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelClienteTelefono)
                    .addComponent(LabelClienteDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxCredito)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        TabbedPaneClientesPago.addTab("Registro de Clientes", PTPClientes);

        PTPPagos.setBackground(new java.awt.Color(255, 255, 255));
        PTPPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelClientePagoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClientePagoNombre.setText("Nombre de Cliente");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("Deuda");

        labelClienteDeuda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteDeuda.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteDeuda.setText("0.00");

        jLabel11.setText("Pago");

        labelClientePago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClientePago.setForeground(new java.awt.Color(70, 106, 124));
        labelClientePago.setText("0.00");

        labelClientePago1.setText("Ticket");

        labelClienteTicket.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteTicket.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteTicket.setText("0000000000");

        jLabel12.setText("Fecha del Pago");

        labelClienteFechaPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteFechaPago.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteFechaPago.setText("--/--/--");

        jLabel14.setText("Cuotas por mes");

        labelClienteCuotasMes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteCuotasMes.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteCuotasMes.setText("0.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClienteDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClientePago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClientePago1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelClienteTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelClienteFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClienteCuotasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelClienteDeuda)
                            .addComponent(labelClientePago)
                            .addComponent(labelClienteTicket)))
                    .addComponent(labelClientePago1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteFechaPago)
                    .addComponent(labelClienteCuotasMes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setText("Fecha del Pago");

        labelClienteFechaIntereses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteFechaIntereses.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteFechaIntereses.setText("--/--/--");

        jLabel15.setText("intereses");

        labelClienteintereses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteintereses.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteintereses.setText("0.00");

        jLabel16.setText("intereses");

        labelClienteCuotas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteCuotas.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteCuotas.setText("0.00");

        jLabel17.setText("Total Intereses");

        labelClienteTicketIntereses.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteTicketIntereses.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteTicketIntereses.setText("0000000000");

        labelClientePago2.setText("Ticket");

        jLabel18.setText("Total a pagar");

        labelClienteInteresesPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelClienteInteresesPago.setForeground(new java.awt.Color(70, 106, 124));
        labelClienteInteresesPago.setText("0.00");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClienteintereses, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClienteFechaIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClienteCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TextFieldClientesCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClientePago2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClienteTicketIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelClienteInteresesPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClienteInteresesPago))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelClienteintereses)
                                    .addComponent(labelClienteCuotas)))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(labelClienteTicketIntereses))
                                .addComponent(labelClientePago2)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelClienteFechaIntereses))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(TextFieldClientesCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        labelReportPagos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelReportPagos.setForeground(new java.awt.Color(70, 106, 124));
        labelReportPagos.setText("Ingrese el pago");

        buttonGroupMonedas.add(RadioButtonIntereses);
        RadioButtonIntereses.setText("Intereses");

        buttonGroupMonedas.add(RadioButtonCuotas1);
        RadioButtonCuotas1.setText("Cuotas");

        javax.swing.GroupLayout PTPPagosLayout = new javax.swing.GroupLayout(PTPPagos);
        PTPPagos.setLayout(PTPPagosLayout);
        PTPPagosLayout.setHorizontalGroup(
            PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTPPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelClientePagoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PTPPagosLayout.createSequentialGroup()
                        .addGroup(PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PTPPagosLayout.createSequentialGroup()
                                .addComponent(RadioButtonCuotas1)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButtonIntereses))
                            .addGroup(PTPPagosLayout.createSequentialGroup()
                                .addComponent(labelReportPagos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldClientesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PTPPagosLayout.setVerticalGroup(
            PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTPPagosLayout.createSequentialGroup()
                .addComponent(labelClientePagoNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonIntereses)
                    .addComponent(RadioButtonCuotas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTPPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReportPagos)
                    .addComponent(TextFieldClientesPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        TabbedPaneClientesPago.addTab("Pagos", PTPPagos);

        javax.swing.GroupLayout PClientesPagoLayout = new javax.swing.GroupLayout(PClientesPago);
        PClientesPago.setLayout(PClientesPagoLayout);
        PClientesPagoLayout.setHorizontalGroup(
            PClientesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PClientesPagoLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(ButtonClienteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ButtonClienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PClientesPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneClientesPago))
        );
        PClientesPagoLayout.setVerticalGroup(
            PClientesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PClientesPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneClientesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PClientesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonClienteCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonClienteAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneClientesPago2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneClientesPago2StateChanged(evt);
            }
        });

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientesMouseClicked(evt);
            }
        });
        TableClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TableClientes);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        TabbedPaneClientesPago2.addTab("Lista de Clientes", jPanel8);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableClientesReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableClientesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientesReportMouseClicked(evt);
            }
        });
        TableClientesReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableClientesReportKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableClientesReport);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        TabbedPaneClientesPago2.addTab("Pago y Reportes", jPanel7);

        jLabel5.setText("Registro por paginas");

        ButtonClientePaginaRight0.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaRight0.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaRight0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Right-12.png"))); // NOI18N
        ButtonClientePaginaRight0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientePaginaRight0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientePaginaRight0ActionPerformed(evt);
            }
        });

        SpinnerPaginasCliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerPaginasClienteStateChanged(evt);
            }
        });

        ButtonClientePaginaLeft0.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaLeft0.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaLeft0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Left-12.png"))); // NOI18N
        ButtonClientePaginaLeft0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientePaginaLeft0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientePaginaLeft0ActionPerformed(evt);
            }
        });

        ButtonClientePaginaLeft.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaLeft.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Left.png"))); // NOI18N
        ButtonClientePaginaLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientePaginaLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientePaginaLeftActionPerformed(evt);
            }
        });

        ButtonClientePaginaRight.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaRight.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClientePaginaRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Right.png"))); // NOI18N
        ButtonClientePaginaRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientePaginaRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientePaginaRightActionPerformed(evt);
            }
        });

        LabelClientePaginador.setText("Paginas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(SpinnerPaginasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(ButtonClientePaginaLeft0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClientePaginaLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClientePaginaRight, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClientePaginaRight0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(TabbedPaneClientesPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(LabelClientePaginador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneClientesPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerPaginasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LabelClientePaginador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonClientePaginaRight0)
                            .addComponent(ButtonClientePaginaLeft0)
                            .addComponent(ButtonClientePaginaLeft)
                            .addComponent(ButtonClientePaginaRight))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PClientesPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PClientesPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TabbedPanePrincipal.addTab("Clientes", jPanel3);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 106, 124));
        jLabel3.setText("Configuraciones");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroupMonedas.add(RadioButtonDolares);
        RadioButtonDolares.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RadioButtonDolares.setText("$.");

        buttonGroupMonedas.add(RadioButtonCordobas);
        RadioButtonCordobas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RadioButtonCordobas.setText("C$.");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 106, 124));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipos de Monedas");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonCordobas)
                    .addComponent(RadioButtonDolares))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(RadioButtonDolares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonCordobas)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1681, Short.MAX_VALUE))
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );

        TabbedPanePrincipal.addTab("Configuraciones", jPanel11);

        ButtonVentas.setBackground(new java.awt.Color(51, 51, 51));
        ButtonVentas.setForeground(new java.awt.Color(51, 51, 51));
        ButtonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Shopping.png"))); // NOI18N
        ButtonVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ButtonClientes1.setBackground(new java.awt.Color(51, 51, 51));
        ButtonClientes1.setForeground(new java.awt.Color(51, 51, 51));
        ButtonClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/people.png"))); // NOI18N
        ButtonClientes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientes1ActionPerformed(evt);
            }
        });

        ButtonConfiguracion.setBackground(new java.awt.Color(51, 51, 51));
        ButtonConfiguracion.setForeground(new java.awt.Color(51, 51, 51));
        ButtonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Settings.png"))); // NOI18N
        ButtonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanePrincipal)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2123, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonVentas)
                    .addComponent(ButtonClientes1)
                    .addComponent(ButtonConfiguracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="CODIGO DE CLIENTE">  
    private ClientesVM cliente;

    private void LabelimageClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelimageClienteMouseClicked

        Objetos.uploadimage.cargarImagen(LabelimageCliente);
    }//GEN-LAST:event_LabelimageClienteMouseClicked

    private void ButtonClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClienteAgregarActionPerformed
        cliente.registrarCliente();
    }//GEN-LAST:event_ButtonClienteAgregarActionPerformed

    private void ButtonClienteCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClienteCancelarActionPerformed
        // TODO add your handling code here:
        cliente.restablecer();
    }//GEN-LAST:event_ButtonClienteCancelarActionPerformed

    private void TextFieldClienteDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteDireccionKeyReleased

        if (TextFieldClienteDireccion.getText().equals("")) {
            LabelClienteDireccion.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteDireccion.setText("Direccion");
            LabelClienteDireccion.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteDireccionKeyReleased

    private void TextFieldClienteTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteTelefonoKeyTyped

        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_TextFieldClienteTelefonoKeyTyped

    private void TextFieldClienteTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteTelefonoKeyReleased

        if (TextFieldClienteTelefono.getText().equals("")) {
            LabelClienteTelefono.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteTelefono.setText("Telefono");
            LabelClienteTelefono.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteTelefonoKeyReleased

    private void TextFieldClienteEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteEmailKeyReleased

        if (TextFieldClienteEmail.getText().equals("")) {
            LabelClienteEmail.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteEmail.setText("Email");
            LabelClienteEmail.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteEmailKeyReleased

    private void TextFieldClienteApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteApellidoKeyTyped
        Objetos.eventos.textKeyPresses(evt);
    }//GEN-LAST:event_TextFieldClienteApellidoKeyTyped

    private void TextFieldClienteApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteApellidoKeyReleased

        if (TextFieldClienteApellido.getText().equals("")) {
            LabelClienteApellido.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteApellido.setText("Apellido");
            LabelClienteApellido.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteApellidoKeyReleased

    private void TextFieldClienteNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteNombreKeyTyped

        Objetos.eventos.textKeyPresses(evt);
    }//GEN-LAST:event_TextFieldClienteNombreKeyTyped

    private void TextFieldClienteNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteNombreKeyReleased

        if (TextFieldClienteNombre.getText().equals("")) {
            LabelClienteNombre.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteNombre.setText("Nombre");
            LabelClienteNombre.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteNombreKeyReleased

    private void TextFieldClienteIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteIdKeyTyped

        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_TextFieldClienteIdKeyTyped

    private void TextFieldClienteIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldClienteIdKeyReleased
        //cambia el color de las etiquetas
        if (TextFieldClienteId.getText().equals("")) {
            LabelClienteId.setForeground(new Color(102, 102, 102));

        } else {
            LabelClienteId.setText("ID");
            LabelClienteId.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextFieldClienteIdKeyReleased

    private void TextFieldClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldClienteIdActionPerformed

    private void ButtonClientePaginaRight0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientePaginaRight0ActionPerformed
        // TODO add your handling code here:
        cliente.paginador("Ultimo");
    }//GEN-LAST:event_ButtonClientePaginaRight0ActionPerformed

    private void ButtonClientePaginaLeft0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientePaginaLeft0ActionPerformed
        // TODO add your handling code here:
        cliente.paginador("Primero");
    }//GEN-LAST:event_ButtonClientePaginaLeft0ActionPerformed

    private void ButtonClientePaginaLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientePaginaLeftActionPerformed
        // TODO add your handling code here:
        cliente.paginador("Anterior");
    }//GEN-LAST:event_ButtonClientePaginaLeftActionPerformed

    private void ButtonClientePaginaRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientePaginaRightActionPerformed
        // TODO add your handling code here:
        cliente.paginador("Siguiente");
    }//GEN-LAST:event_ButtonClientePaginaRightActionPerformed

    private void SpinnerPaginasClienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerPaginasClienteStateChanged
        // TODO add your handling code here:
        cliente.registroPaginas();
    }//GEN-LAST:event_SpinnerPaginasClienteStateChanged

    private void TableClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableClientesKeyReleased

        if (TableClientes.getSelectedRows().length > 0) {
            cliente.obtenerCliente();
        }
    }//GEN-LAST:event_TableClientesKeyReleased

    private void TableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientesMouseClicked
        if (TableClientes.getSelectedRows().length > 0) {
            cliente.obtenerCliente();
        }
    }//GEN-LAST:event_TableClientesMouseClicked

    private void TabbedPaneClientesPagoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneClientesPagoStateChanged
        switch (TabbedPaneClientesPago.getSelectedIndex()) {
            case 0:
                if (TabbedPaneClientesPago2.getSelectedIndex() > 0) {
                    TabbedPaneClientesPago2.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.registroPaginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                TabbedPaneClientesPago2.setSelectedIndex(1);
                cliente.registroPaginas();
                break;

        }

    }//GEN-LAST:event_TabbedPaneClientesPagoStateChanged

    private void TabbedPaneClientesPago2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneClientesPago2StateChanged
        switch (TabbedPaneClientesPago2.getSelectedIndex()) {
            case 0:
                if (TabbedPaneClientesPago.getSelectedIndex() > 0) {
                    TabbedPaneClientesPago.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.registroPaginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                TabbedPaneClientesPago.setSelectedIndex(1);
                cliente.registroPaginas();
                break;

        }
    }//GEN-LAST:event_TabbedPaneClientesPago2StateChanged

    private void TableClientesReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientesReportMouseClicked
        if (TableClientesReport.getSelectedRows().length > 0) {
            cliente.obtenerReporteCliente();
        }
    }//GEN-LAST:event_TableClientesReportMouseClicked

    private void TableClientesReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableClientesReportKeyReleased
        if (TableClientesReport.getSelectedRows().length > 0) {
            cliente.obtenerReporteCliente();
        }
    }//GEN-LAST:event_TableClientesReportKeyReleased

    private void ButtonClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientes1ActionPerformed
        ArrayList<JLabel> label = new ArrayList();
        label.add(LabelClienteId);
        label.add(LabelClienteNombre);
        label.add(LabelClienteApellido);
        label.add(LabelClienteEmail);
        label.add(LabelClienteTelefono);
        label.add(LabelClienteDireccion);
        label.add(LabelimageCliente);
        label.add(LabelClientePaginador);

        label.add(labelClientePagoNombre);
        label.add(labelClienteDeuda);
        label.add(labelClientePago);
        label.add(labelClienteTicket);
        label.add(labelClienteFechaPago);
        label.add(labelClienteCuotasMes);
        label.add(labelClienteintereses);
        label.add(labelClienteFechaIntereses);
        label.add(labelClienteCuotas);
        label.add(labelClienteTicketIntereses);
        label.add(labelClienteFechaIntereses);
        label.add(labelClienteInteresesPago);

        ArrayList<JTextField> textField = new ArrayList();
        textField.add(TextFieldClienteId);
        textField.add(TextFieldClienteNombre);
        textField.add(TextFieldClienteApellido);
        textField.add(TextFieldClienteEmail);
        textField.add(TextFieldClienteTelefono);
        textField.add(TextFieldClienteDireccion);
        Object[] objects = {
            checkboxCredito,
            TableClientes,
            SpinnerPaginasCliente,
            TableClientesReport
        };
        cliente = new ClientesVM(objects, label, textField);
        TabbedPanePrincipal.setSelectedIndex(1);
        ButtonClientes1.setEnabled(false);
        ButtonConfiguracion.setEnabled(true);
    }//GEN-LAST:event_ButtonClientes1ActionPerformed

    ConfiguracionesVM config;
    private void ButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfiguracionActionPerformed

        TabbedPanePrincipal.setSelectedIndex(2);
        ButtonClientes1.setEnabled(true);
        ButtonConfiguracion.setEnabled(false);
        config = new ConfiguracionesVM(radio);
    }//GEN-LAST:event_ButtonConfiguracionActionPerformed

    /// <editor-fold>  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClienteAgregar;
    private javax.swing.JButton ButtonClienteCancelar;
    private javax.swing.JButton ButtonClientePaginaLeft;
    private javax.swing.JButton ButtonClientePaginaLeft0;
    private javax.swing.JButton ButtonClientePaginaRight;
    private javax.swing.JButton ButtonClientePaginaRight0;
    private javax.swing.JButton ButtonClientes1;
    private javax.swing.JButton ButtonConfiguracion;
    private javax.swing.JButton ButtonVentas;
    private javax.swing.JLabel LabelClienteApellido;
    private javax.swing.JLabel LabelClienteDireccion;
    private javax.swing.JLabel LabelClienteEmail;
    private javax.swing.JLabel LabelClienteId;
    private javax.swing.JLabel LabelClienteNombre;
    private javax.swing.JLabel LabelClientePaginador;
    private javax.swing.JLabel LabelClienteTelefono;
    private javax.swing.JLabel LabelimageCliente;
    private javax.swing.JPanel PClientesPago;
    private javax.swing.JPanel PTPClientes;
    private javax.swing.JPanel PTPPagos;
    private javax.swing.JRadioButton RadioButtonCordobas;
    private javax.swing.JRadioButton RadioButtonCuotas1;
    private javax.swing.JRadioButton RadioButtonDolares;
    private javax.swing.JRadioButton RadioButtonIntereses;
    private javax.swing.JSpinner SpinnerPaginasCliente;
    private javax.swing.JTextField TFBuscarCliente;
    private javax.swing.JTabbedPane TabbedPaneClientesPago;
    private javax.swing.JTabbedPane TabbedPaneClientesPago2;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTable TableClientes;
    private javax.swing.JTable TableClientesReport;
    private javax.swing.JTextField TextFieldClienteApellido;
    private javax.swing.JTextField TextFieldClienteDireccion;
    private javax.swing.JTextField TextFieldClienteEmail;
    private javax.swing.JTextField TextFieldClienteId;
    private javax.swing.JTextField TextFieldClienteNombre;
    private javax.swing.JTextField TextFieldClienteTelefono;
    private javax.swing.JTextField TextFieldClientesCuotas;
    private javax.swing.JTextField TextFieldClientesPago;
    private javax.swing.ButtonGroup buttonGroupMonedas;
    private javax.swing.JCheckBox checkboxCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelClienteCuotas;
    private javax.swing.JLabel labelClienteCuotasMes;
    private javax.swing.JLabel labelClienteDeuda;
    private javax.swing.JLabel labelClienteFechaIntereses;
    private javax.swing.JLabel labelClienteFechaPago;
    private javax.swing.JLabel labelClienteInteresesPago;
    private javax.swing.JLabel labelClientePago;
    private javax.swing.JLabel labelClientePago1;
    private javax.swing.JLabel labelClientePago2;
    private javax.swing.JLabel labelClientePagoNombre;
    private javax.swing.JLabel labelClienteTicket;
    private javax.swing.JLabel labelClienteTicketIntereses;
    private javax.swing.JLabel labelClienteintereses;
    private javax.swing.JLabel labelReportPagos;
    // End of variables declaration//GEN-END:variables
}
