/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lunes.Vista;

/**
 *
 * @author Alcides Blandon
 */
public class FrmVendedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmVendedor
     */
    public FrmVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPInformacionVendedor = new javax.swing.JPanel();
        jLbNombres = new javax.swing.JLabel();
        jTFVentaBruto = new javax.swing.JTextField();
        jLbTipoVenta = new javax.swing.JLabel();
        jCBTipoVenta = new javax.swing.JComboBox<>();
        jLbVentaBruto = new javax.swing.JLabel();
        jTFNombres = new javax.swing.JTextField();
        jLbTarifaComision = new javax.swing.JLabel();
        jTFTarifaComison = new javax.swing.JTextField();
        jLbComisonPagar = new javax.swing.JLabel();
        jTFComisionPagar = new javax.swing.JTextField();
        jBImprimir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jPVistaPreliminar = new javax.swing.JPanel();
        jSPVistaPreliminar = new javax.swing.JScrollPane();
        jTAVistaPreliminar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPInformacionVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion del Vendedor"));

        jLbNombres.setText("Nombres");

        jLbTipoVenta.setText("Tipo de Venta");

        jCBTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al por Mayor", "Al Detalle" }));
        jCBTipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoVentaActionPerformed(evt);
            }
        });

        jLbVentaBruto.setText("Venta Bruto");

        jLbTarifaComision.setText("Tarifa/Comision");

        jLbComisonPagar.setText("Comision a Pagar");

        jTFComisionPagar.setEnabled(false);

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPInformacionVendedorLayout = new javax.swing.GroupLayout(jPInformacionVendedor);
        jPInformacionVendedor.setLayout(jPInformacionVendedorLayout);
        jPInformacionVendedorLayout.setHorizontalGroup(
            jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionVendedorLayout.createSequentialGroup()
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInformacionVendedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbComisonPagar)
                            .addComponent(jLbTarifaComision)
                            .addComponent(jLbVentaBruto)
                            .addComponent(jLbTipoVenta))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInformacionVendedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBTipoVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFVentaBruto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTarifaComison, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFComisionPagar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInformacionVendedorLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPInformacionVendedorLayout.setVerticalGroup(
            jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionVendedorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbNombres)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTipoVenta)
                    .addComponent(jCBTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbVentaBruto)
                    .addComponent(jTFVentaBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTarifaComision)
                    .addComponent(jTFTarifaComison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbComisonPagar)
                    .addComponent(jTFComisionPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPInformacionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImprimir)
                    .addComponent(jBLimpiar))
                .addGap(31, 31, 31))
        );

        jPVistaPreliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Vista Preliminar de Impresion"));

        jTAVistaPreliminar.setColumns(20);
        jTAVistaPreliminar.setRows(5);
        jSPVistaPreliminar.setViewportView(jTAVistaPreliminar);

        javax.swing.GroupLayout jPVistaPreliminarLayout = new javax.swing.GroupLayout(jPVistaPreliminar);
        jPVistaPreliminar.setLayout(jPVistaPreliminarLayout);
        jPVistaPreliminarLayout.setHorizontalGroup(
            jPVistaPreliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSPVistaPreliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        jPVistaPreliminarLayout.setVerticalGroup(
            jPVistaPreliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVistaPreliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPVistaPreliminar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPInformacionVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPVistaPreliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPInformacionVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPVistaPreliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoVentaActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBImprimir;
    public javax.swing.JButton jBLimpiar;
    public javax.swing.JComboBox<String> jCBTipoVenta;
    private javax.swing.JLabel jLbComisonPagar;
    private javax.swing.JLabel jLbNombres;
    private javax.swing.JLabel jLbTarifaComision;
    private javax.swing.JLabel jLbTipoVenta;
    private javax.swing.JLabel jLbVentaBruto;
    private javax.swing.JPanel jPInformacionVendedor;
    private javax.swing.JPanel jPVistaPreliminar;
    private javax.swing.JScrollPane jSPVistaPreliminar;
    public javax.swing.JTextArea jTAVistaPreliminar;
    public javax.swing.JTextField jTFComisionPagar;
    public javax.swing.JTextField jTFNombres;
    public javax.swing.JTextField jTFTarifaComison;
    public javax.swing.JTextField jTFVentaBruto;
    // End of variables declaration//GEN-END:variables
}
