/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LUNES;

import LUNES.SGIS.FrmNUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Alcides Blandon
 */
public class MAdministrar extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public MAdministrar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MNUsuario = new javax.swing.JMenuItem();
        MUtilidades = new javax.swing.JMenu();
        jMIUtilidades = new javax.swing.JMenuItem();
        MAyuda = new javax.swing.JMenu();
        MAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Administrar");

        MNUsuario.setMnemonic('x');
        MNUsuario.setText("Usuario");
        MNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(MNUsuario);

        menuBar.add(fileMenu);

        MUtilidades.setMnemonic('e');
        MUtilidades.setText("Utilidades");

        jMIUtilidades.setText("Mantenimiento");
        jMIUtilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUtilidadesActionPerformed(evt);
            }
        });
        MUtilidades.add(jMIUtilidades);

        menuBar.add(MUtilidades);

        MAyuda.setMnemonic('h');
        MAyuda.setText("Ayuda");

        MAcerca.setMnemonic('a');
        MAcerca.setText("Acerca de");
        MAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAcercaActionPerformed(evt);
            }
        });
        MAyuda.add(MAcerca);

        menuBar.add(MAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNUsuarioActionPerformed
        
        FrmNUsuario fmrUsuario = new FrmNUsuario();
        
        desktopPane.add(fmrUsuario);
        fmrUsuario.toFront();
        fmrUsuario.show();
    }//GEN-LAST:event_MNUsuarioActionPerformed

    private void MAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAcercaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informacion Software \n"
                + "Version del producto: SGIS 1.00 (2019)", "Sistema de Gestion", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_MAcercaActionPerformed

    private void jMIUtilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUtilidadesActionPerformed
        // TODO add your handling code here:
        MAdministrar mAdministrar = new MAdministrar();
        
        desktopPane.add(mAdministrar);
        mAdministrar.toFront();
        mAdministrar.show();
    }//GEN-LAST:event_jMIUtilidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAcerca;
    private javax.swing.JMenu MAyuda;
    private javax.swing.JMenuItem MNUsuario;
    private javax.swing.JMenu MUtilidades;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMIUtilidades;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
