/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viernes.Vista;

/**
 *
 * @author Alcides Blandon
 */
public class JfrmReciboEnvio extends javax.swing.JFrame {

    /**
     * Creates new form ReciboEnvio
     */
    public JfrmReciboEnvio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEnvioRetiro = new javax.swing.ButtonGroup();
        lbComprobante = new javax.swing.JLabel();
        tfComprobante = new javax.swing.JTextField();
        panelPrincipal = new javax.swing.JPanel();
        lbEntidad = new javax.swing.JLabel();
        cmbEntidad = new javax.swing.JComboBox<>();
        lbFecha = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        rbRetiro = new javax.swing.JRadioButton();
        rbEnvio = new javax.swing.JRadioButton();
        panelEmisor = new javax.swing.JPanel();
        lbCedulaE = new javax.swing.JLabel();
        tfCedulaE = new javax.swing.JTextField();
        tfClienteE = new javax.swing.JTextField();
        lbClienteE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDireccionE = new javax.swing.JTextArea();
        lbDireccionE = new javax.swing.JLabel();
        panelReceptor = new javax.swing.JPanel();
        lbCedulaR = new javax.swing.JLabel();
        tfCedularR = new javax.swing.JTextField();
        tfClienteR = new javax.swing.JTextField();
        lbClienteR = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDireccionR = new javax.swing.JTextArea();
        lbDireccionR = new javax.swing.JLabel();
        panelFInal = new javax.swing.JPanel();
        lbMoneda = new javax.swing.JLabel();
        cmbMoneda = new javax.swing.JComboBox<>();
        lbTasaCambio = new javax.swing.JLabel();
        tfTasaCambio = new javax.swing.JTextField();
        lbMonto = new javax.swing.JLabel();
        tfMonto = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lbImporte = new javax.swing.JLabel();
        tfImporte = new javax.swing.JTextField();
        tfComision = new javax.swing.JTextField();
        lbComision = new javax.swing.JLabel();
        lbTotalPagar = new javax.swing.JLabel();
        tfTotalPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbComprobante.setText("Comprobante");

        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbEntidad.setText("Entidad");

        cmbEntidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco", "Finaciera", "Casa de cambio" }));

        lbFecha.setText("Fecha");

        bgEnvioRetiro.add(rbRetiro);
        rbRetiro.setText("Retiro");

        bgEnvioRetiro.add(rbEnvio);
        rbEnvio.setText("Envio");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbEnvio)
                .addGap(18, 18, 18)
                .addComponent(rbRetiro)
                .addGap(53, 53, 53))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEntidad)
                    .addComponent(cmbEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEnvio)
                    .addComponent(rbRetiro))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelEmisor.setBorder(javax.swing.BorderFactory.createTitledBorder("Emisor"));

        lbCedulaE.setText("Cedula");

        lbClienteE.setText("Cliente");

        taDireccionE.setColumns(20);
        taDireccionE.setRows(5);
        jScrollPane1.setViewportView(taDireccionE);

        lbDireccionE.setText("Direccion");

        javax.swing.GroupLayout panelEmisorLayout = new javax.swing.GroupLayout(panelEmisor);
        panelEmisor.setLayout(panelEmisorLayout);
        panelEmisorLayout.setHorizontalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbClienteE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDireccionE))
                        .addGap(18, 18, 18)
                        .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfClienteE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addComponent(lbCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelEmisorLayout.setVerticalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCedulaE)
                    .addComponent(tfCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteE)
                    .addComponent(tfClienteE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbDireccionE))
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelReceptor.setBorder(javax.swing.BorderFactory.createTitledBorder("Receptor"));

        lbCedulaR.setText("Cedula");

        lbClienteR.setText("Cliente");

        taDireccionR.setColumns(20);
        taDireccionR.setRows(5);
        jScrollPane2.setViewportView(taDireccionR);

        lbDireccionR.setText("Direccion");

        javax.swing.GroupLayout panelReceptorLayout = new javax.swing.GroupLayout(panelReceptor);
        panelReceptor.setLayout(panelReceptorLayout);
        panelReceptorLayout.setHorizontalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addComponent(lbDireccionR)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReceptorLayout.createSequentialGroup()
                                .addComponent(lbCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(panelReceptorLayout.createSequentialGroup()
                                .addComponent(lbClienteR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfClienteR, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCedularR, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        panelReceptorLayout.setVerticalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCedulaR)
                    .addComponent(tfCedularR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteR)
                    .addComponent(tfClienteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbDireccionR)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panelFInal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbMoneda.setText("Moneda");

        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cordoba", "Dolares", " " }));
        cmbMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMonedaItemStateChanged(evt);
            }
        });
        cmbMoneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbMonedaMouseClicked(evt);
            }
        });
        cmbMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonedaActionPerformed(evt);
            }
        });

        lbTasaCambio.setText("Tasa Cambio");

        lbMonto.setText("Monto");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbImporte.setText("Importe");

        tfImporte.setEnabled(false);

        tfComision.setEnabled(false);

        lbComision.setText("Comision");

        lbTotalPagar.setText("Total a pagar");

        tfTotalPagar.setEnabled(false);

        javax.swing.GroupLayout panelFInalLayout = new javax.swing.GroupLayout(panelFInal);
        panelFInal.setLayout(panelFInalLayout);
        panelFInalLayout.setHorizontalGroup(
            panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFInalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFInalLayout.createSequentialGroup()
                        .addComponent(lbImporte)
                        .addGap(18, 18, 18)
                        .addComponent(tfImporte))
                    .addGroup(panelFInalLayout.createSequentialGroup()
                        .addComponent(lbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTasaCambio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFInalLayout.createSequentialGroup()
                        .addComponent(tfTasaCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFInalLayout.createSequentialGroup()
                        .addComponent(lbComision)
                        .addGap(18, 18, 18)
                        .addComponent(tfComision, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotalPagar)
                        .addGap(18, 18, 18)
                        .addComponent(tfTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        panelFInalLayout.setVerticalGroup(
            panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFInalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMoneda)
                    .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTasaCambio)
                    .addComponent(tfTasaCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMonto)
                    .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImporte)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbComision)
                        .addComponent(tfComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelFInalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotalPagar)
                            .addComponent(tfTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelFInal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(lbComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(panelEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(panelReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbComprobante)
                            .addComponent(tfComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelFInal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonedaActionPerformed

    }//GEN-LAST:event_cmbMonedaActionPerformed

    private void cmbMonedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMonedaMouseClicked

    }//GEN-LAST:event_cmbMonedaMouseClicked

    private void cmbMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMonedaItemStateChanged
        

    }//GEN-LAST:event_cmbMonedaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmReciboEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmReciboEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmReciboEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmReciboEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmReciboEnvio().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEnvioRetiro;
    public javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbEntidad;
    public javax.swing.JComboBox<String> cmbMoneda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCedulaE;
    private javax.swing.JLabel lbCedulaR;
    private javax.swing.JLabel lbClienteE;
    private javax.swing.JLabel lbClienteR;
    private javax.swing.JLabel lbComision;
    private javax.swing.JLabel lbComprobante;
    private javax.swing.JLabel lbDireccionE;
    private javax.swing.JLabel lbDireccionR;
    private javax.swing.JLabel lbEntidad;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbImporte;
    private javax.swing.JLabel lbMoneda;
    private javax.swing.JLabel lbMonto;
    private javax.swing.JLabel lbTasaCambio;
    private javax.swing.JLabel lbTotalPagar;
    private javax.swing.JPanel panelEmisor;
    private javax.swing.JPanel panelFInal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelReceptor;
    private javax.swing.JRadioButton rbEnvio;
    private javax.swing.JRadioButton rbRetiro;
    private javax.swing.JTextArea taDireccionE;
    private javax.swing.JTextArea taDireccionR;
    private javax.swing.JTextField tfCedulaE;
    private javax.swing.JTextField tfCedularR;
    private javax.swing.JTextField tfClienteE;
    private javax.swing.JTextField tfClienteR;
    public javax.swing.JTextField tfComision;
    private javax.swing.JTextField tfComprobante;
    private javax.swing.JTextField tfFecha;
    public javax.swing.JTextField tfImporte;
    public javax.swing.JTextField tfMonto;
    public javax.swing.JTextField tfTasaCambio;
    public javax.swing.JTextField tfTotalPagar;
    // End of variables declaration//GEN-END:variables
}
